### ISSUE TITLE
MIlestone: Kanban Board Setup

### ISSUE THREAD

**Issue by geekelo** [geekelo/fenaj-schedula_API#25]
Link to Kanban Board:  [https://github.com/users/geekelo/projects/3](https://github.com/users/geekelo/projects/3)
Team size; 5

PICTORIAL REPRESENTATIONS:
1.
![Screenshot from 2023-11-29 11-57-46](https://github.com/geekelo/fenaj-schedula_API/assets/102464578/01d70ebd-e795-4508-98e7-b60131f5f32b)

2.
![Screenshot from 2023-11-29 11-58-55](https://github.com/geekelo/fenaj-schedula_API/assets/102464578/4ae9e369-b37a-4f43-85c4-cccdf82eb749)

3.
![Screenshot from 2023-11-29 11-59-31](https://github.com/geekelo/fenaj-schedula_API/assets/102464578/20fe5106-e467-4566-949f-701506200479)

**Comment by Meltrust** [comment]
Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, FOR WHICH THE LINK DOES NOT WORK. PLEASE ENSURE ITS NOT PRIVATE.

![image](https://github.com/geekelo/fenaj-schedula_API/assets/57421823/623a9d54-0460-4958-a512-9465bdf6e9fb)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
